const keyMap = new Map([
	['trigonometry_inverse', { display: '', expression: '' }],
	['pi', { display: 'π', expression: 'Math.PI' }],
	['euler', { display: 'e', expression: 'Math.E' }],
	['clear', { display: '', expression: '' }],
	['backspace', { display: '', expression: '' }],
	['square', { display: '^2', expression: 'Math.pow(' }],
	['reciprocal', { display: '1/', expression: '' }],
	['ceiling', { display: '⌈', expression: 'Math.ceil(' }],
	['exponent', { display: '*10^', expression: '10 * Math.pow(' }],
	['modulus', { display: '%', expression: '%' }],
	['root', { display: '√', expression: 'Math.root(' }],
	['left_parenthesis', { display: '(', expression: '(' }],
	['right_parenthesis', { display: ')', expression: ')' }],
	['factorial', { display: '!', expression: '' }],
	['divide', { display: '/', expression: '/' }],
	['power', { display: '^', expression: 'Math.pow(' }],
	['seven', { display: '7', expression: '7' }],
	['eight', { display: '8', expression: '8' }],
	['nine', { display: '9', expression: '9' }],
	['multiply', { display: '*', expression: '*' }],
	['ten_power', { display: '10^', expression: 'Math.pow(' }],
	['four', { display: '4', expression: '4' }],
	['five', { display: '5', expression: '5' }],
	['six', { display: '6', expression: '6' }],
	['minus', { display: '-', expression: '-' }],
	['logarithm', { display: 'log', expression: 'Math.log2(' }],
	['one', { display: '1', expression: '1' }],
	['two', { display: '2', expression: '2' }],
	['three', { display: '3', expression: '3' }],
	['addition', { display: '+', expression: '+' }],
	['natural_log', { display: 'ln', expression: 'Math.log2(' }],
	['sign_change', { display: '±', expression: '' }],
	['zero', { display: '0', expression: '0' }],
	['decimal', { display: '.', expression: '.' }],
	['equals', { display: '=', expression: '' }],
]);

export { keyMap };
